// src/core/components/header/Header.tsx
import { InputText } from 'primereact/inputtext';
import { Link } from 'react-router-dom';

export const Header = () => {
  return (
    <header
      className='py-4 px-[10vw] flex justify-between content-center w-full bg-white border-b border-slate-800 fixed z-10'
    >
      <section className='flex gap-10 content-center leading-8'>
        <h1 className='font-bold text-[20px]'>IT Quizlet</h1>
        <Link to={''}>
          <h2 className='text-[17px]'>Home</h2>
        </Link>
        <Link to={'/quiz/list'}>
          <h2 className='text-[17px]'>My library</h2>
        </Link>
      </section>

      <span className='p-input-icon-left'>
        <i className='pi pi-search pl-[12px]'/>
        <InputText
          className='input'
          placeholder='Пошук'
        />
      </span>

      <section className='flex gap-10'>
        <Link to={'/auth/login'}>
          <button className='btn outlined w-[93px] h-full'>Увійти</button>
        </Link>
        <Link to={'/quiz/create'}>
          <button className='btn filled w-[93px] h-full'>Створити</button>
        </Link>
      </section>
    </header>
  )
}

// src/app/core/components/header/header.component.ts
import {Component, inject} from '@angular/core';
import {RouterModule} from "@angular/router";
import {AuthService} from "../../services/auth.service";

@Component({
  selector: 'app-header',
  imports: [RouterModule],
  standalone: true,
  template: `
    <header
      class='py-4 px-[6vw] flex justify-between content-center w-full bg-white border-b border-slate-800 fixed z-10'
    >
      <section class='flex gap-10 content-center leading-8'>
        <h1 class='font-bold text-[20px]'>IT Quizlet</h1>
        <h2 class='text-[17px] cursor-pointer' routerLink="/">Home</h2>
        
        @if (authService.loggedUser()) {
          <h2 class='text-[17px] cursor-pointer' routerLink="/quiz/list">Quizes</h2>
          <button class='btn filled w-[93px] h-full' routerLink="/quiz/create">Create</button>
        }
      </section>

      <section class='flex gap-10'>
        @if (!authService.loggedUser()) {
          <button class='btn outlined w-[93px] h-full' routerLink="/auth/login">Login</button>
        } @else {
          <button class='btn outlined w-[93px] h-full' (click)="onLogout()">Logout</button>
        }
      </section>
        
    </header>
  `,
})
export class HeaderComponent {
  readonly authService = inject(AuthService);

  onLogout() {
    this.authService.logout();
  }
}
