// src/app/pages/quiz/pages/quiz-list/quiz-list.component.ts
import { Component } from '@angular/core';
import {ItemSliderComponent} from "../../../../shared/components/item-slider/item-slider.component";
import {TagModule} from "primeng/tag";
import {AvatarModule} from "primeng/avatar";
import {RouterModule} from "@angular/router";

@Component({
  selector: 'app-quiz-list',
  imports: [
    ItemSliderComponent,
    TagModule,
    AvatarModule,
    RouterModule
  ],
  standalone: true,
  template: `
    <div class="flex flex-col gap-4 p-6">
      <h1 class="px-12 font-bold text-2xl">Popular</h1>

      <div class="flex flex-wrap gap-12 p-6">
          <div
            class='card flex flex-col gap-6 flex-auto min-w-[40%] items-start cursor-pointer hover:shadow-lg'
            routerLink="/quiz/item"
        >
          <h1>Test name</h1>
          <p-tag value="40 terms" [style]="{ background: 'black' }"/>

            <div class="flex gap-2 mt-12 content-center items-center">
              <p-avatar
                label="Z"
                shape="circle"
              />
              <span class="">uZer</span>
              
              <p-tag value="Teacher" [style]="{ background: 'black' }"/>
            </div>
          </div>
      </div>

      <app-item-slider/>
    </div>;
  `
})
export class QuizListComponent {

}

// src/pages/quiz/quiz-list/QuizList.tsx
import {Tag} from "primereact/tag";
import {Avatar} from "primereact/avatar";
import {ItemsSlider} from "../../../shared/components/items-slider.tsx";
import {Link} from "react-router-dom";

export const QuizList = () => {
  // TODO: integrate with BE
  const quizes = [0, 1, 2, 3];

  return <div className="flex flex-col gap-4 p-6">
    <h1 className="px-12 font-bold text-2xl">Popular</h1>

    <div className="flex flex-wrap gap-12 p-6">
      {
        quizes.map(() =>
          <Link
            className='card flex flex-col gap-6 flex-auto min-w-[40%] items-start cursor-pointer hover:shadow-lg'
            to={'/quiz/item'}
          >
            <h1>Test name</h1>
            <Tag value="40 terms" style={{background: 'black'}}/>

            <div className="flex gap-2 mt-12 content-center items-center">
              <Avatar
                label="Z"
                shape="circle"
              />
              <span className="">uZer</span>
              <Tag value="Teacher" style={{background: 'black'}}/>
            </div>
          </Link>
        )
      }
    </div>

    <ItemsSlider/>
  </div>;
}
