// src/app/pages/quiz/pages/quiz-create/quiz-create.component.ts
import { Component } from '@angular/core';
import {InputTextModule} from "primeng/inputtext";
import {TextareaModule} from "primeng/textarea";
import {DropdownModule} from "primeng/dropdown";

@Component({
  selector: 'app-quiz-create',
  imports: [
    InputTextModule,
    TextareaModule,
    DropdownModule
  ],
  standalone: true,
  template: `
    <div class="flex flex-col gap-12 px-[20vw]">
      <div class="flex flex-col gap-4">
        <h1 class="text-3xl font-bolder">Create quiz</h1>
        <input pInputText placeholder="Enter title" class="input"/>
        <input pTextarea placeholder="Add description" class="input max-h-[20rem] min-h-[5rem]"/>

        <div class="flex gap-6">
          <p-dropdown placeholder="Select tag" class="input !p-0"/>
          <p-dropdown placeholder="Select Level" class="input !p-0"/>
        </div>
      </div>

      <div class="flex flex-col gap-4 pb-12">
        <div class="card flex flex-col gap-12 !px-4 !py-2 !pb-6">
          <span
            class="text-sm border-b border-slate-300 pb-2 flex justify-between"
          >
            {{ 0 }}
            <i class="pi pi-trash cursor-pointer" (click)="null"></i>
          </span>

          <div class="flex items-stretch gap-4">
            <input
              class='w-full border-[#9D9D9D] border-b-[1px] focus:outline-none focus:ring-0 text-sm'
              placeholder="Term"
            />

            <input
              class='w-full border-[#9D9D9D] border-b-[1px] focus:outline-none focus:ring-0 text-sm'
              placeholder="Definition"
            />
          </div>
        </div>

        <i class="pi pi-plus-circle text-2xl cursor-pointer self-center" (click)="null"></i>
      </div>

    </div>
  `
})
export class QuizCreateComponent {
}

// src/pages/quiz/quiz-create/QuizCreate.tsx
import {InputText} from "primereact/inputtext";
import {InputTextarea} from "primereact/inputtextarea";
import {Dropdown} from "primereact/dropdown";
import {useState} from "react";

export const QuizCreate = () => {
  const [terms, setTerms] = useState(Array.from({ length: 2 }).map((_, i) => i));

  const onTermDelete = (index: number) => {
    setTerms(terms.filter((_, i) => i !== index));
  }

  const onAddTerm = () => {
    setTerms([ ...terms, terms.length ]);
  }


  return <div className="flex flex-col gap-12 px-[20vw]">
    <div className="flex flex-col gap-4">
      <h1 className="text-3xl font-bolder">Create quiz</h1>
      <InputText placeholder="Enter title" className="input"/>
      <InputTextarea placeholder="Add description" className="input max-h-[20rem] min-h-[5rem]" rows={5} />

      <div className="flex gap-6">
        <Dropdown placeholder="Select tag" className="input !p-0"/>
        <Dropdown placeholder="Select Level" className="input !p-0"/>
      </div>
    </div>

    <div className="flex flex-col gap-4 pb-12">
      {
        terms.map((_, i) =>
          <div className="card flex flex-col gap-12 !px-4 !py-2 !pb-6">
            <span
              className="text-sm border-b border-slate-300 pb-2 flex justify-between"
            >
              { i }
              <i className="pi pi-trash cursor-pointer" onClick={() => onTermDelete(i)}/>
            </span>

            <div className="flex items-stretch gap-4">
              <input
                className='w-full border-[#9D9D9D] border-b-[1px] focus:outline-none focus:ring-0 text-sm'
                placeholder="Term"
              />

              <input
                className='w-full border-[#9D9D9D] border-b-[1px] focus:outline-none focus:ring-0 text-sm'
                placeholder="Definition"
              />
            </div>
          </div>
        )
      }

      <i className="pi pi-plus-circle text-2xl cursor-pointer self-center" onClick={() => onAddTerm()}/>
    </div>

  </div>;
}
